baseURL: "https://hkust-prof-qu-test.netlify.app"
languageCode: en-us
title: Demo for Hugo FYM
theme: PaperMod

params:
  homeInfoParams:
    Title: 'Hello Stranger'
    Content: 'Welcome!'
  socialIcons:
    - name: facebook
      url: 'www.facebook.com'
    - name: twitter
      url: 'www.twitter.com'
    - name: github
      url: 'www.github.com'

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
menu:
  main:
    - identifier: categories
      name: Home3
      url: /categories/
      weight: 10
    - identifier: tags
      name: Research2
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 40
